### ISSUE TITLE
make it offline-capable

### ISSUE THREAD

**Issue by derhuerst** [juliuste/deutsche-post#1]
would be great to have a build script that downloads the data, so that the module can be used/bundled in apps that don't need an internet connection.

if you would like to keep the module as is, i will create a module on top instead. 🎉

**Comment by juliuste** [comment]
Since there probably will be some minor changes in the postal code data from time to time, I would rather keep the "live version" and outsource the "dump" to another module. Feel free to do so 👍

**Comment by derhuerst** [comment]
Created a static list of PLZs at [`german-postal-codes`](https://github.com/derhuerst/german-postal-codes).
